### ISSUE TITLE
Changes to readme and About screen

### ISSUE THREAD

**Issue by JPLeBreton** [squintdev/nftscii#1]
As per the MIT license I am legally fine with this fork existing and I am in favor of it having a different name. I would appreciate it if you could do two things:

1) Remove all the links in the Readme. As this is a fork, I will not be providing any support whatsoever for it.

2) Remove my name, those of my old patrons, and my special thanks credits from the About screen (Starting at line 72 in ui_info_dialog.py). For the contributor credit sections, I would say leave those in and anyone who doesn't want to be named there can let you know (I doubt they are aware of this fork).

You're under no legal obligation to do these things, it would just be the decent thing to do. Should take 10 minutes, tops. Thanks!
I will not be responding to any comments in this issue thread except to answer questions or provide guidance on the above requests.

**Comment by squintdev** [comment]
I will absolutely make those changes. Thanks JP.
